
// This file has been generated by the GUI designer. Do not modify.
namespace oplab1bolyuk
{
	public partial class СWindow
	{
		private global::Gtk.VBox vbox6;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Button menubut;

		private global::Gtk.Button resultbut;

		private global::Gtk.Label info;

		private global::Gtk.Table table1;

		private global::Gtk.Button but1;

		private global::Gtk.Button but2;

		private global::Gtk.Button but3;

		private global::Gtk.Button but4;

		private global::Gtk.Button but5;

		private global::Gtk.Button but6;

		private global::Gtk.Button but7;

		private global::Gtk.Button but8;

		private global::Gtk.Button but9;

		private global::Gtk.Button butnul;

		private global::Gtk.Button clearbut;

		private global::Gtk.Button dotbut;

		private global::Gtk.HBox hbox2;

		private global::Gtk.Button divisbut;

		private global::Gtk.Button multbut;

		private global::Gtk.Button minusbut;

		private global::Gtk.Button plusbut;

		private global::Gtk.Label label5;

		protected virtual void Build()
		{
			
		}
	}
}
