
// This file has been generated by the GUI designer. Do not modify.
namespace oplab1bolyuk
{
	public partial class Swin
	{
		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget oplab1bolyuk.Swin
			this.Name = "oplab1bolyuk.Swin";
			this.Title = global::Mono.Unix.Catalog.GetString("Swin");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show();
		}
	}
}
